name: Blog CI/CD

# 触发条件：在 push 到 main 分支后触发,然后推送同步到gitee
on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  resume-cicd:
    name: gulp Builder
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup node
        # 设置 node.js 环境
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        # 设置包缓存目录，避免每次下载.缓存
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install gulp dependencies
        # 下载 hexo-cli 脚手架及相关安装包
        run: |
          npm install gulp gulp-cli -g
          npm install

      - name: Generate files
        # 清除打包文件 编译 markdown 文件
        run: |
          hexo clean
          hexo generate
        #   hexo deploy
      - name: Deploy hexo blog
        env:
          # Github 仓库
          GITHUB_REPO: github.com/xcbt9527/m-blog
          # Coding 仓库
          # CODING_REPO: e.coding.net/yifanzheng/blogs.git
          # Gitee 仓库
          GITEE_REPO: gitee.com/xuanbi/m-blog
        # 将编译后的博客文件推送到指定仓库
        run: |
          cd ./public && git init && git add .
          git config user.name "xcbt9527"
          git config user.email "764567192@qq.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git branch -M gh-pages
          git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" gh-pages:gh-pages
          git config user.name "玄笔"
          git push --force --quiet "https://xuanbi:${{ secrets.GITEE_ACCOUNT_TOKEN }}@$GITEE_REPO" gh-pages:gh-pages
        #   git push --force --quiet "https://RoYFbFDSfM:${{ secrets.CODING_TOKEN }}@$CODING_REPO" master:master
